# -*- coding: utf-8 -*-
"""grade_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWhxBY_aMSzCQXHJjLdcGVvpMew1MiuW
"""

def grade_system(): # define function for grade

  marks = int(input('Enter the marks (0-100):')) # take input from the user as int

  while marks < 0 or marks > 100:
    print('Invalid input try again!')
    marks = int(input('Enter the marks again:')) # the loop will run while the user enter the number from (0-100)

  if 90 <= marks <= 100: # check the grade according to the marks given and sending message
    print('Grade A ')
    print('Excellent!')

  elif 80 <= marks <= 89:
    print('Grade B')
    print('Great job!')


  elif 70 <= marks <= 79:
    print('Grade C')
    print('Good work!')


  elif 60 <= marks <= 69:
    print('Grade D')
    print('keep trying!')

  else:
    print('Grade F')
    print('Never give up')

grade_system() # call the function